POST /register
Host: 127.0.0.1:5000
Content-Type: application/json

{
  "username": "cool_user",
  "firstName": "Jora",
  "lastName": "Jora"
}

###

GET /users
Host: 127.0.0.1:8080


###

POST /postMessage
Host: 127.0.0.1:8080
Content-Type: application/json

{
  "author": "cool_user",
  "text": "Text too"
}

###

GET /allMessages
Host: 127.0.0.1:8080

###

GET /lastMessages?sinceId=1
Host: 127.0.0.1:8080

###
POST https://sample-message-server.herokuapp.com/postMessage
Content-Type: application/json

{
    "author": "eugene",
    "text": "Hello everyone"
}